import requests, os, json
def fetch_collection_addons(api_key, collection_id):
    url = "https://api.steampowered.com/ISteamRemoteStorage/GetCollectionDetails/v1/"
    payload = {
        'collectioncount': 1,
        'publishedfileids[0]': collection_id
    }

    response = requests.post(url, data=payload)
    response.raise_for_status()

    data = response.json()
    print(json.dumps(data, indent=2))
    children = data['response']['collectiondetails'][0].get('children', [])

    addon_ids = [child['publishedfileid'] for child in children if child['filetype'] == 0]
    return addon_ids

def write_lua_file(addon_ids, output_file='collection.lua'):
    with open(output_file, 'w') as lua_file:
        lua_file.write('-- Auto-generated by GMod Workshop Collection Tool made by Trakatz :)\n\n')
        for addon_id in addon_ids:
            lua_file.write(f'resource.AddWorkshop("{addon_id}")\n')

    print(f"[✔] Lua-File '{output_file}' succsesfully created with {len(addon_ids)} Addons!")

def main(api_key, collection_id):
    try:
        addon_ids = fetch_collection_addons(api_key, collection_id)
        if not addon_ids:
            print("[!] Keine Addons gefunden oder Collection ist leer.")
            return
        write_lua_file(addon_ids)
    except Exception as e:
        print(f"[❌] Error: {e}")

if __name__ == '__main__':
    if os.name == 'nt':
        os.system("title GMod Workshop Collection Tool")
    
    while True:
        print()
        print("=== GMod Workshop Collection Tool ===")
        collection_id = input("📦 Workshop Collection ID> ").strip()
        api_key = input("🔑 Steam WebAPI Key (Leave blank for tutorial on how to get it)> ").strip()
        if api_key == "":
            print("Please visit this page to get your API Key:")
            print("👉 https://steamcommunity.com/dev/apikey")
            input("Press Enter to continue...")
            # Do not exit, loop again for new inputs
        else:
            main(api_key, collection_id)
